server:
  port: 4040

spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:4010
          predicates:
            - Path=/api/user/**
        - id: hotel-service
          uri: http://localhost:4020
          predicates:
            - Path=/api/hotels/**
        - id: rating-service
          uri: http://localhost:4030
          predicates:
            - Path=/api/ratings/**
